GET http://localhost:3001/ex
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzgwOTY4NjQ4fQ.AYaAJ-Ge4bob02GRJ_Ljhgij7LqhQIGIHFuYHelTDFc

###
# use this to separate reqs; also need newline after content type before body

POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}


###

POST http://localhost:4001/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsInBhc3N3b3JkIjoiJDJiJDEwJEhFMlo3b1UzdVZtdHVwN1V0RFlrQU9iNWVPb1Vyd0RpanNKR2oxdkovQTMzcjUzTW4wcmx5IiwiaWF0IjoxNzgxMTQwMDU5fQ.UCk7AMBy6ENtiWp2N78-Fq61dR6pOTc6JsR_YSvdPoo"
}

###

POST http://localhost:4001/login
Content-Type: application/json

{
    "username": "testuser1",
    "password": "testpassword1"
}

###

POST http://localhost:4001/register
Content-Type: application/json

{
    "username": "testuser1",
    "password": "testpassword1"
}


###

DELETE http://localhost:4001/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsInBhc3N3b3JkIjoiJDJiJDEwJEhFMlo3b1UzdVZtdHVwN1V0RFlrQU9iNWVPb1Vyd0RpanNKR2oxdkovQTMzcjUzTW4wcmx5IiwiaWF0IjoxNzgxMTQwMDU5fQ.UCk7AMBy6ENtiWp2N78-Fq61dR6pOTc6JsR_YSvdPoo"
}



